### ISSUE TITLE
Adjusting the size of the calendar

### ISSUE THREAD

**Issue by say-when** [airbnb/HorizonCalendar#110]
I've got a question. I've been evaluating the calendar component for a project, and keep getting an assert "Calendar metrics and size resulted in a negative-or-zero amount of remaining height" when placing it in a container view (about 375 x 375 points). I have to size it up to about 385 height to get it to appear. I couldn't find anything in the docs about sizing the calendar, the day items or adjusting the layout beyond the CalendarViewContent .with methods. Is there something I'm missing?

**Comment by bryankeller** [comment]
Hi @say-when - I know that this is a frustrating behavior. At a minimum, the error that's printed should be improved to explain why the issue is occurring. I also think we could improve the docs for this - I'll do that soon.

If you must fit your calendar in a 375x375 container, you'll need to increase the number of months visible using the horizontal layout config. By displaying more months horizontally, each month will have smaller day items to fit the width, which will also decrease the height, allowing you to fit your calendar in the 375pt tall container.

Try doing this:

```swift
CalendarView(
  visibleDateRange: startDate...endDate,
  monthsLayout: .horizontal(options: HorizontalMonthsLayoutOptions(maximumFullyVisibleMonths: 2)))
```

Try changing the `maximumFullyVisibleMonths` until the content fits correctly. Hope this helps!

**Comment by bryankeller** [comment]
Starting in version 1.11.0 (just released), `CalendarView` now has an `intrinsicContentSize.height` equal to the exact amount of space needed to fit all of the rows of a month, given the current width / other layout metrics. That means that you can add a horizontally-scrolling `CalendarView` to your view hierarchy, constrain its width, and the height will be set based on the `intrinsicContentSize`.

**Comment by Ksen17** [comment]
Version 1.11.0
<img width="401" alt="image" src="https://user-images.githubusercontent.com/8882963/161248843-dcaae907-9467-4580-b1b0-8c91215ea6cf.png">
