### ISSUE TITLE
Is it possible to programmatically select a date instead of waiting for the user to tap on a day?

### ISSUE THREAD

**Issue by cassfinn** [airbnb/HorizonCalendar#123]
When the calendar first loads it would be great if the selectedDay could be programmatically selected vs. waiting for the user to tap on a date.  Not sure if that is already possible.  

From what I can see, it looks like we'd have to create a Day instance in the code, but I can't see how to do that since it's private. It appears that the user has to tap a day on the calendar in order for the daySelectionHandler to be called.

Use case:  I'm showing a tableView below the calendarView that lists items in the selected day and would like to load the calendar and automatically have the code select a specific date in order to show the tableView items in that specific date.

**Comment by bryankeller** [comment]
Hey @cassfinn - HorizonCalendar / CalendarView has no concept of selected vs. unselected dates - that's state that you should manage in your own feature code. If you want something to appear as "selected," then you need to provide a different `CalendarItemModel` for a "selected" styled day in your `dayItemModelProvider` closure.

I think the example project makes this a bit confusing, since you're right that `Day`s cannot be initialized by library consumers like yourself. What you should do instead is convert the `Day` to a `Date` (using your `Calendar` instance), then use that to decide whether or not to show a selected-style view or not.

I've updated the example project to make this more clear. PR for it is here: https://github.com/airbnb/HorizonCalendar/pull/127 - If you copy the changes I made [here](https://github.com/airbnb/HorizonCalendar/pull/127/files#diff-d5de5296657b3413782cccdaf3df1b2d30b481b7ca76869a37ecdf1e4713db73R21-R31) in your own project, you should be able to get a default selected day!
