### ISSUE TITLE
Any thoughts on adopting the Time library?

### ISSUE THREAD

**Issue by Mordil** [airbnb/HorizonCalendar#138]
Dave DeLong has done a fantastic job of disambiguating time from dates in his [**Time**](https://github.com/davedelong/time) package.

Any thoughts on adopting that as the foundation for the date concepts so that users of this library can have a better time with dealing with dates instead of having to use boilerplate (that even this library needs, but doesn't expose) to remove the concept of time?

**Comment by bryankeller** [comment]
Hi Dave! This project will likely never pull in any third-party dependencies. We have our own data/time code internally at Airbnb, and I also don't want to force people who use `HorizonCalendar` to also need to adopt another library.

 https://github.com/davedelong/time does appear to be a fantastic library. My recommendation would be to create some extensions / compatibility shims in your own project so that the two projects can be used together. We've done something similar internally at Airbnb to make `HorizonCalendar` play nicely with our internal Date/time library. You could always share your compatibility shims here, and if they're thorough and well-documented, I'd be happy to link to them from this project's README 🙂
