### ISSUE TITLE
Not calculating size and rendering Calendar for version 1.11 or higher but works on 1.8.0

### ISSUE THREAD

**Issue by felipeflorencio** [airbnb/HorizonCalendar#157]
Hello,

I have been using the calendar with version 1.8 without any problem with rendering the calendar view.

After update to the version 1.11 it just doesn't render it anymore, no code change.

And besides trying to set the content again at viewWillAppear just to make sure my view is completed nothing change.

Also is find to find any documentation mention something like "If you want to force layout user this"

Of course, tried to use setNeedsLayout and layoutIfNeeded but no success

**Comment by bryankeller** [comment]
Hi @felipeflorencio - I suspect this is due to this change https://github.com/airbnb/HorizonCalendar/pull/150

Previously, if you were using `MonthsLayout.horizontal` (horizontally-scrolling layout), then you had to guess how tall your calendar should be and set a height constraint that provided enough space for all of the calendar's content to fit in the vertical dimension. This was complicated and error-prone. See issues: https://github.com/airbnb/HorizonCalendar/issues/88, https://github.com/airbnb/HorizonCalendar/issues/110, and https://github.com/airbnb/HorizonCalendar/issues/125.

Starting in `v1.11`, `CalendarView` has an intrinsic content size. Now, you only need to give your `CalendarView` instance an X/Y position and width constraint. The height is determined based on the width. You can also set a height constraint if you'd like to make the calendar taller or shorter than its intrinsic height.

-----

If you can post a screenshot of your view hierarchy (a screenshot of the Xcode view debugger would be helpful too), then I can help you figure out exactly what's wrong. I also think that if you look at the Example project, you can see how the constraints are set up https://github.com/airbnb/HorizonCalendar/blob/master/Example/HorizonCalendarExample/HorizonCalendarExample/Demo%20View%20Controllers/DemoViewController.swift#L49-L73

**Comment by bryankeller** [comment]
@felipeflorencio going to close this out since I haven't heard from you. Hope you got things working!
