### ISSUE TITLE
Change height of day of week header

### ISSUE THREAD

**Issue by mfbx9da4** [airbnb/HorizonCalendar#218]
Thanks for building this brilliant calendar library. 

I think I'm going to have to patch this library to be able to support a custom height for the day of week header unless I am missing something? I've tried to modify `heightOfDaysOfTheWeekRowInMonth() -> CGFloat` to return a custom height but this causes the `daysOfTheWeekRowSeparator` to be placed incorrectly. I would greatly appreciate any guidance for changing this height. 

Thanks

**Comment by ecunha-ta** [comment]
I dont know if this is related, if not let me know, but I am having issues when I set to ```pinDaysOfWeekToTop``` I have some issues with the header view, is there a way to set its frame ? 

My issue is that I can see the days passing above the week days and I can see them passing on the right and left side in the bar while I scroll :(

![screenshot](https://user-images.githubusercontent.com/77671235/229113017-a955c6c0-f331-4de2-bd26-ae49c2151632.png)

**Comment by bryankeller** [comment]
@mfbx9da4 @ecunha-ta just merged https://github.com/airbnb/HorizonCalendar/issues/218, which lets you configure the aspect ratio of days of the week with a `.dayOfWeekAspectRatio(_:)` content modifier.

**Comment by ecunha-ta** [comment]
Hey @bryankeller thanks for the quick help and answer but the change you did does not solve the problem I reported.. should it?

When I scroll I can still see the circles passing on the `days of week` bar.. I mean the width of the bar is too small for the content of the days.. anyway we can allow the bar to fill the width of the screen? Otherwise we can see the content on the sides while scrolling.. 

<img width="518" alt="Screenshot 2023-04-12 at 12 21 08" src="https://user-images.githubusercontent.com/77671235/231442393-b651d897-4d29-469d-b63c-65e91a0c0c3a.png">
