### ISSUE TITLE
Ability to configure scrolling behaviour

### ISSUE THREAD

**Issue by Pattio** [airbnb/HorizonCalendar#25]
Hey, 

first of all, thank you for open-sourcing this neat library! 

Secondly, I wanted to ask you: would you consider adding some kind of ability to configure scrolling behaviour (perhaps to `MonthsLayout` enum via `LayoutOptions`)? Because I wanted to implement horizontal calendar with snapping like behaviour (where you have single month shown on the screen and then using swipe gesture or buttons move to next/previous month) and the only way how I managed to achieve that was by going into view hierarchy and disabling scroll on `NoContentInsetAdjustmentScrollView` which feels kinda hacky as it would stop working if at some point you decide to move `scrollview` somewhere else.

Also, I was curious: does `HorizonCalendar` support RTL layout? Because in order to achieve proper scrolling on RTL I had to change `transform` of `CalendarView`

Thanks

**Comment by bryankeller** [comment]
Hi @Pattio - this is definitely a feature that we want to add support for! And I agree, manually messing with that internal scroll view is probably not a good idea.

I think we could probably support the programatic scrolling via buttons by having your code call:

```swift
public func scroll(
    toMonthContaining dateInTargetMonth: Date,
    scrollPosition: CalendarViewScrollPosition,
    animated: Bool)
```

But we'd still need the snapping behavior. I'll get around to working on this in the next few weeks!


----


As for RTL layout, I wonder what that would look like? Would the order of months change for the horizontal layout? I guess we don't support that right now, but that's a great callout. PRs are welcome if you'd like to tackle that one, but otherwise I'll leave this open so it's being tracked.

**Comment by Pattio** [comment]
Awesome, thank you for the response. Yeah programmatic scroll works pretty nice, just the fact that I need to mess with the `scrollview` to disable the scroll on it, rubs me the wrong way 😄

Regarding RTL it the biggest issues for me was the scroll animation as it should be performed in the opposite direction. I managed to solve it by transforming `CalendarView` by setting its `transform` to `CGAffineTransform(scaleX: -1, y: 1)` it's definitely not the best solution, but it works for me.

Anyway, once again thank you for your work!

**Comment by tareksabry1337** [comment]
@bryankeller First of all thanks for the incredible work on this, the amount of work and customization possible in this library is insane ! 
I'd like to ask if there's an update on the snapping behavior ? Is it coming anytime soon ?

**Comment by bryankeller** [comment]
@tareksabry1337 I'm working on snapping behavior next (just finished fixing a few bugs and adding RTL support cc @Pattio) ... stay tuned 🙂

**Comment by OttoFI** [comment]
@bryankeller Thanks for working hard on this amazing calendar.
Any updates on the snapping behavior? 
Looking forward to this feature!

**Comment by bryankeller** [comment]
@OttoFI @Pattio @tareksabry1337 thanks all for your patience. v1.7.0 is now live with support for horizontal pagination.
