### ISSUE TITLE
Can we start re-adding tags for new releases?

### ISSUE THREAD

**Issue by emans** [airbnb/HorizonCalendar#279]
Hi [bryankeller](https://github.com/bryankeller) , I was trying to integrate this on our project via SPM but instead of pointing to a commit or branch point to a version, but I noticed there's none since january.. Would it be possible to get back to release tagging? 

Thanks for the project.
Regards

**Comment by bryankeller** [comment]
I'm aiming to tag a new release in the next couple of weeks. For now, you can just point SPM / Cocoapods / Carchate to the latest commit hash, instead of a version tag. The next release is going to be 2.0.0, which includes many enhancements, but also some breaking API changes if folks haven't moved off of deprecated APIs in a while.

**Comment by emans** [comment]
Thanks! :D
