### ISSUE TITLE
Calendar not being refreshed when new events are fetched from the sever

### ISSUE THREAD

**Issue by mustiikhalil** [airbnb/HorizonCalendar#29]
First of all, thanks for this amazing library. 

I've noticed the following issue when using the library, the data is not being refreshed properly after fetching data from the server. I am attaching screenshots at the bottom. 

example:
```swift
  var events: [String: Any] = [:]

  var presenter: CalendarPresenterDelegate!

  override func viewDidLoad() {
      super.viewDidLoad()
      /// some networking logic
      presenter.fetchEvents()
  }

  override func makeContext() -> CalendarViewContent {

        let startDate = Date()
        let endDate = calendar.date(from: DateComponents(year: 2021, month: 12, day: 31))!

        return CalendarViewContent(calendar: calendar,
                                   visibleDateRange: startDate...endDate,
                                   monthsLayout: .horizontal(monthWidth: min(view.frame.height, view.frame.width) - 40))
            .withDayItemProvider { day -> CalendarItem<EventLabel, Day> in
                let date = self.calendar.date(from: day.components)!
                let isSelectedDay = self.selectedDates.contains(date)
                return CalendarItem<EventLabel, Day>(
                    viewModel: day,
                    styleID: isSelectedDay ? "SelectedDayLabelStyle" : "DayLabelStyle",
                    buildView: {
                        return EventLabel()
                    },
                    updateViewModel: self.setupEvent)
            }
            .withInterMonthSpacing(16)
            .withVerticalDayMargin(8)
            .withHorizontalDayMargin(8)
    }

    func setEvents(events: [String: Any]) {
        self.events = events
        let newContent = makeContent()
        calendarView.setContent(newContent)
    }

    override func setupEvent(label: EventLabel, day: Day) {

        label.text = "\(day.day)"
        // clear the events
        label.hasNoEvents()

        if isSelectedDay {
            label.backgroundColor = Colors.colorAccent
        } else {
            label.backgroundColor = isToday ? Colors.colorPrimary : .clear
        }

        guard let object = getEvents(date: date) else {
            return
        }

        if (object["event1"] as? Bool) == true {
            label.hasEvent1()
            label.textColor = .lightGray
            return
        }

        if (object["event2"] as? [String])?.isEmpty == false {
            label.hasEvent2()
        }
    }
```

This is what we get after `setEvents` being called, however the result we need is in the second image:
image 1
<img width="634" alt="Screen Shot 2020-07-14 at 7 11 14 PM" src="https://user-images.githubusercontent.com/26250654/87449751-42244c80-c606-11ea-8cc3-1fe79fec2bc9.png">
image 2
<img width="632" alt="Screen Shot 2020-07-14 at 7 11 00 PM" src="https://user-images.githubusercontent.com/26250654/87449429-df32b580-c605-11ea-8555-9e001c51f7cd.png">

PS: if we scroll to September and back the UI refreshes and the UI updates properly. it seems as if the 
`calendarView.setContent(newContent)` is not setting the content properly.

**Comment by bryankeller** [comment]
@mustiikhalil glad you're finding the library useful 🙂 

Some ideas:
- Is `setEvents` being called on the main thread? If not, that would definitely cause weird UI quirks. I should probably add an assert in `setContent` to prevent this / make it obvious what's wrong
- Have you set a breakpoint in `setupEvent` to make sure it gets called for each visible day after you call `setContent`? `HorizonCalendar` should invoke that function `n` times after you call `setContent`, where `n` is the number of currently visible days.

If neither of those suggestions lead you to an answer, if you could post some sample code (try to repro in the included example project if it's easy) I'd be happy to help investigate more!

**Comment by mustiikhalil** [comment]
@bryankeller thanks for your reply. I looked at it today, and it seems that your second suggestion is what's actually happening. Where the setupEvent is not being called after calling `calendarView.setContent(newContent)` nor if we kept it as a closure. I've attached a small repo that has some demo code. 

- `setEvents(events: [String: Any])` is being called by the presenter.

- we replace the old content with the new content, which means that `makeContent` is being called properly

- `withDayItemProvider` is being invoked twice which seems to be the proper behavior too.

- `CalendarItem`'s `buildView` and `updateViewModel` are being called once only. I understand why buildView is called once, however `updateViewModel` should be invoked twice

[repo for the test code](https://github.com/mustiikhalil/TestCalendar)

**Comment by bryankeller** [comment]
@mustiikhalil ah, I see the problem! Thanks a bunch for the repro case... although I should have caught this from your original code snippet 😅

The problem is that you're using the `updateViewModel` closure to do configuration that is not captured by your view model. Internally, `HorizonCalendar` will only update views whose view model has changed - that's why the `viewModel` you pass in must be equatable - so that we know when a view has changed.

You'll need to refactor your code like this:

```swift

struct EventData: Equatable {
    let day: Day
    let hasEvent1: Bool
    let hasEvent2: Bool
}

...

 return CalendarItem<EventLabel, EventData>(
                    viewModel: EventData(day: day, hasEvent1: object.event1, hasEvent2: object.event2),
                    styleID: "Default",
                    buildView: {
                        return EventLabel()
                    },
                    updateViewModel: { label, eventData in
                        ...
                    }
```


----


This is a failure on my part for not making this clearer in the documentation. The key with these `CalendarItem` instances is that they try to force you to make your UIView a pure function of its view model, but there's no way to enforce this completely without rewriting UIKit.


----

One other side note - you only need to provide a custom styleID if you're using the same UIView subclass but with different initialization / setup properties. For example, if you used a `UILabel` with a red font for selected days, and a `UILabel` with a black font for unselected days, and this color was configured in the `buildView` closure, then you'd need to provide a different `styleID` for each variation. You can see this in the `HorizonCalendar` example code. If I had built the selection demo view controller by making the selected state part of the view model instead, then I would not need to use a `styleID`. Maybe that property needs a different name, or better documentation 🙂

**Comment by bryankeller** [comment]
This has really got me thinking about ways to make this way simpler for developers... stay tuned 😄

**Comment by mustiikhalil** [comment]
@bryankeller Thanks! That makes complete sense actually. plus I see why you would need a new custom StyleID for an eventful cell. I was trying stuff out which is why I moved the colors into the `updateViewModel`, instead of the `buildView` since I wanted to see if I can simply update the UI without completely repainting the UI for that label (for the events).  
But overall, amazing component!

**Comment by bryankeller** [comment]
Awesome, really glad that fixed the issue for you! 

For what it's worth, I think having the color dots be part of your view model makes a lot of sense, particularly if that's data that might change a lot due to API response updates. If you want to speed up your rendering / repaint cost, you could implement those dot indicators using `CoreGraphics` in `drawRect`, or by just setting a dot view's `isHidden` / `backgroundColor` property if you want to keep using `UIView`s to represent the dots. I think either of those options will be cheaper than adding / removing subviews dynamically, which will cause auto layout constraints to churn a bit 🙂 

Best of luck!

**Comment by mustiikhalil** [comment]
@bryankeller Yeah I know, I was thinking of using `CAShapelayer` actually for the dots, however for a fast proof of concept I used a normal UIView

**Comment by bryankeller** [comment]
@mustiikhalil version 1.4.0 makes it much harder to introduce bugs like this. Check out the updated README.md and example project to see how to use the new API 🙂 The existing API has been marked as deprecated, so after updating, you should see the deprecations called out.

**Comment by mustiikhalil** [comment]
@bryankeller thanks for the ping! will definitely check it out!

**Comment by isaacthedeveloper** [comment]
@mustiikhalil Great design, Can I ask for you get the dots below the date? i.e the red and green ones?

**Comment by mustiikhalil** [comment]
@isaacthedeveloper well we subclassed `UILabel` and then we draw the circles according to the event type we have. we are using `CoreGraphic` as @bryankeller suggested above 

> For what it's worth, I think having the color dots be part of your view model makes a lot of sense, particularly if that's data that might change a lot due to API response updates. If you want to speed up your rendering / repaint cost, you could implement those dot indicators using CoreGraphics in drawRect, or by just setting a dot view's isHidden / backgroundColor property if you want to keep using UIViews to represent the dots. I think either of those options will be cheaper than adding / removing subviews dynamically, which will cause auto layout constraints to churn a bit
