### ISSUE TITLE
Scrolling issue on MacCatalyst

### ISSUE THREAD

**Issue by kennic** [airbnb/HorizonCalendar#43]
It's going blank when you fast scrolling by mouse on Mac Catalyst

**Comment by bryankeller** [comment]
Weird - it seems like Catalyst `UIScrollView` behaves a bit differently from iOS / iPadOS. On those, updating the content inset at scroll time will cause the `UIScrollView` to decelerate if it approaches the boundary defined by the content inset. On Mac Catalyst, it seems like the scroll view will scroll to a target content offset that is no longer possible given the updated content inset.

I'm looking into a workaround... thanks for reporting!

**Comment by bryankeller** [comment]
I've done some more digging, and it seems like this bug is reproducible even with UICollectionView if you give each item a very large estimated height. The large estimated height results in a scroll view with a much larger `contentSize.height` than it really needs. If you scroll down quickly (one hard swipe on the trackpad), the collection view's target offset will be far beyond the actual content size that's determined as items are scrolled past and self sized.

I'll file a radar - ideally, Mac's scroll view would not work any differently than iOS'. In the man time, I think we can work around this by adding some checks in scrollViewDidScroll to ensure that we don't scroll way past the boundary of the content.

**Comment by bryankeller** [comment]
@kennic this is fixed in v1.6.7, just released.
