### ISSUE TITLE
CalendarView does not show in UIStackView

### ISSUE THREAD

**Issue by JackMoseley2001** [airbnb/HorizonCalendar#54]
Hello,

Thank you for this great and easy to use library.

I'm facing an issue when adding the CalendarView to a UIStackView where nothing will display from the calendar view. I've attached a photo.

https://imgur.com/a/jPIeEvQ

Any help would be greatly appreciated

**Comment by bryankeller** [comment]
Hi @JackMoseley2001 ! Glad you're enjoying using `HorizonCalendar`! I'm pretty sure the issue here is that you haven't given `HorizonCalendar` a height constraint. `UIStackView` uses `intrinsicContentSize` to resolve the layout of views in a stack view, so for views that don't have an `intrinsicContentSize` (like `UITableView`, `UICollectionView`, and `HorizonCalendar.CalendarView`), you'll need to specify your own height constraint by doing something like this:

```swift
calendarView.heightAnchor.constraint(equalToConstant: 200).isActive = true
```

**Comment by JackMoseley2001** [comment]
Thank you for your reply.

I tried using the height constraint which worked (although it did keep breaking the constraint but not a new problem for me!).
Resorted into wrapping it in a different view and then using fillEqually on the stack view which gave me the result I needed.

Thank you for your help!
