### ISSUE TITLE
How to disable future date in calendar?

### ISSUE THREAD

**Issue by jalpeshgoti201** [airbnb/HorizonCalendar#64]
Hello Team, You did a great job. I have an issue with how to disable & enable future dates in the calendar.
Hoping to hear from you soon.

**Comment by bryankeller** [comment]
Hi @jalpeshgoti201 - what do you mean "disable" future dates? 

Do you mean make it so that they can't be tapped? You can simply not respond to taps in your `daySelectionHandler` if you want those dates to do nothing when tapped.

Do you mean make it so that they appear greyed out? You can do this by using a different set of InvariantViewProperties to configure your day view in the `dayItemModelProvider` closure. 

Let me know if these options make sense!

**Comment by bryankeller** [comment]
@jalpeshgoti201 can we close this issue or do you still have questions? If you can provide more details then I'll be able to helo more.

**Comment by jalpeshgoti201** [comment]
Thanks for helping us.
