### ISSUE TITLE
Selection handler gets called multiple times?

### ISSUE THREAD

**Issue by rs658726** [airbnb/HorizonCalendar#72]
Hello,

Thanks for making this awesome calendar open source.

I noticed that the selection handler gets called multiple times in a row once a date is selected and It's creating issues on our end because we are calling a delegate function. Is this normal behavior?

**Comment by rs658726** [comment]
Nevermind, the delegate gets called after makecontent and because makecontent gets called multiple times, the delegate gets also called multiple times.

**Comment by bryankeller** [comment]
I just want to make sure I understand correctly - what delegate is getting called because `makeContent()` is called? In the example project included with the repo, that function doesn't have any side effects besides returning an instance of `CalendarViewContent`. Is this an issue specific to your code? Thanks for clarifying!
