### ISSUE TITLE
Question: Is there a way to initialize the calendar with a selected day or day range?

### ISSUE THREAD

**Issue by taleslemes** [airbnb/HorizonCalendar#87]
I could only show a selected day or day range by clicking on the calendar date. 
I would like to know if it is possible to show to the user a pre-selected date.
thank you

**Comment by bryankeller** [comment]
Hey @taleslemes - this part of the README should walk you through adding a day range indicator programmatically https://github.com/airbnb/HorizonCalendar#adding-a-day-range-indicator

The key thing to understand is that the entire state of the calendar is driven by `CalendarViewContent`. If you want something to show up initially, then the initial `CalendarViewContent` needs to include the configuration necessary to make that thing show up. In this case, the initial `CalendarViewContent` that you provide to the `CalendarView` instance needs to have its day range indicator item model provider set so that the calendar knows to show this.
