### ISSUE TITLE
Horizontal Calendar Leading and Trailing sizes are different

### ISSUE THREAD

**Issue by bekzodrakhmatof** [airbnb/HorizonCalendar#98]
Hi Airbnb Team,

Thank you for applying pagination to the calendar.

For some reason my calendar leading and trailing spaces are different. I want to use full screen width for horizontal calendar.

See the attached image.

![IMG_0649](https://user-images.githubusercontent.com/23249828/106437630-cd890080-64b8-11eb-9fad-53e88468908b.jpg)

Thank you for the answer!

**Comment by bryankeller** [comment]
Hi @bekzodrakhmatof, is your calendar constrained so the leading and trailing edges are equal to the superview's leading and trailing edges? Something like this:

```swift
NSLayoutConstraint.activate([
        calendarView.leadingAnchor.constraint(equalTo: view.leadingAnchor),
        calendarView.trailingAnchor.constraint(equalTo: view.trailingAnchor),
        calendarView.topAnchor.constraint(equalTo: view.topAnchor),
        calendarView.bottomAnchor.constraint(equalTo: view.bottomAnchor),
      ])
```

Maybe you're constraining to `view.layoutMarginsGuide.leadingAnchor` instead of `view.leadingAnchor`?

You can also set the `calendarView.layoutMargins` property if you'd like to add some left / right padding from the edge while still constraining to the edge of the superview. Let me know if this helps!

**Comment by bekzodrakhmatof** [comment]
Hi @bryankeller, Thank you for the reply.

I was using storyboard and my both leading and trailing constraints are 0 for both side and I got the above result.

As you can see in the image leading space but no space on the trailing. So I gave -8 for for the leading and 8 for the trailing. As a result I get what exactly I want but it's a bit strange.

<img width="372" alt="Screen Shot 2021-02-03 at 10 53 37 AM" src="https://user-images.githubusercontent.com/23249828/106686695-20280100-660e-11eb-82b1-c50f3b318f94.png">

So the result is this.

![IMG_0661](https://user-images.githubusercontent.com/23249828/106686904-890f7900-660e-11eb-8d7a-5e92edcf8bd1.jpg)

I am not sure if its intentionally done for flowing calendar but for full screen paginatable calendar looks strange.

My current workaround is fine for my design but as I said its a bit strange.

Thank you!

**Comment by bryankeller** [comment]
@bekzodrakhmatof I think the problem is UIKit automatically sets some layout margins on the view. The default margins are `UIEdgeInsets(top: 8.0, left: 8.0, bottom: 8.0, right: 8.0)`, which explains the 8pt offset.

To fix this, in your view controller, add the following code:

```swift
calendarView.layoutMargins = .zero
```

if you do this, you should be able to fix your constraints in interface builder so that there is not a -8pt offset. Hope this helps!

**Comment by bekzodrakhmatof** [comment]
Thank you very much for the support!

**Comment by bryankeller** [comment]
No problem! Let me know if this fixes the problem 🙂

**Comment by bekzodrakhmatof** [comment]
Yes, it works. Thanks again!
